### ISSUE TITLE
Node.js 20 Upgrade

### ISSUE THREAD

**Issue by jmakowski1123** [openedx/platform-roadmap#340] opened 2024-03-28 22:11 UTC
This is a placeholder ticket for all documentation related to the node.js upgrade.
```[tasklist]
### Tasks
- [ ] https://github.com/openedx/public-engineering/issues/229
```

**Comment by kdmccormick** [comment] 2024-03-29 18:14
@brian-smith-tcril , is there another Node upgrade ticket that we could either link here or replace this one with?

**Comment by jmakowski1123** [comment] 2024-03-29 18:55
> [@brian-smith-tcril](https://github.com/brian-smith-tcril) , is there another Node upgrade ticket that we could either link here or replace this one with?

If there are tickets already in existence, please link them in this ticket. This ticket functions as the Master index, with all other relevant tickets and other documentation, etc.

**Comment by brian-smith-tcril** [comment] 2024-03-29 20:49
I know of https://github.com/openedx/edx-platform/issues/31937, I can do a bit more digging, I've also updated https://github.com/openedx/edx-platform/pull/34311 to link to this issue

**Comment by kdmccormick** [comment] 2024-06-13 13:45
This is a duplicate of https://github.com/openedx/platform-roadmap/issues/362

**Closed by kdmccormick** 2024-06-13 13:45 UTC
